import { useEffect } from "react";
import Head from "next/head";
import { useDispatch, useSelector } from "react-redux";
import UserCard from "../components/UserCard";
import { getUsers } from "../store/userSlice";
import Loading from "../components/Loading";

const Home = () => {
  const dispatch = useDispatch();

  const { loading, allUsers, error } = useSelector((state) => state.users);

  useEffect(() => {
    dispatch(getUsers());
  }, []);

  return (
    <div>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {loading ? (
        <Loading />
      ) : error ? (
        <div>Something Went Wronge !</div>
      ) : allUsers.length ? (
        <div className="flex flex-wrap">
          {allUsers.map((user) => (
            <UserCard key={user.id} userData={user} />
          ))}
        </div>
      ) : (
        "No User Found"
      )}
    </div>
  );
};

export default Home;

// npm run dev
// json-server --watch db.json --port 3001
